cppassist: cppassist::vector< T, SIMD_SIZE > Class Template Reference
cppassist::vector< T, SIMD_SIZE > Class Template Reference
#include <cppassist/include/cppassist/simd/vector.h>
Public Types
using primitive_type = T
using value_type = value< primitive_type, simd_size >
using allocator = cppassist::aligned_allocator< value_type, simd_size *sizeof(primitive_type)>
using iterator = typename std::vector< value_type, allocator >::iterator
using const_iterator = typename std::vector< value_type, allocator >::const_iterator
using size_type = typename std::vector< value_type, allocator >::size_type
using reference = typename std::vector< value_type, allocator >::reference
using const_reference = typename std::vector< value_type, allocator >::const_reference
Public Member Functions
vector ()
vector (size_t count)
vector (T *data, size_t count)
vector (const vector &data)
vector (vector &&data)
T * data ()
const T * data () const
size_t size () const
void resize (size_t size)
bool empty ()
void clear ()
size_t chunkSize () const
value< T, SIMD_SIZE > & chunk (size_t i)
const value< T, SIMD_SIZE > & chunk (size_t i) const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
T * valueBegin ()
const T * valueBegin () const
T * valueEnd ()
const T * valueEnd () const
Protected Attributes
size_t m_size
std::vector< value< T, simd_size >, allocator > m_data
Member Typedef Documentation
primitive_type
template<typename T, size_t SIMD_SIZE = CPPASSIST_SIMD_SIZE> using cppassist::vector< T, SIMD_SIZE >::primitive_type = T
value_type
template<typename T, size_t SIMD_SIZE = CPPASSIST_SIMD_SIZE> using cppassist::vector< T, SIMD_SIZE >::value_type = value<primitive_type, simd_size>
allocator
template<typename T, size_t SIMD_SIZE = CPPASSIST_SIMD_SIZE> using cppassist::vector< T, SIMD_SIZE >::allocator = cppassist::aligned_allocator<value_type, simd_size * sizeof(primitive_type)>
iterator
template<typename T, size_t SIMD_SIZE = CPPASSIST_SIMD_SIZE> using cppassist::vector< T, SIMD_SIZE >::iterator = typename std::vector<value_type, allocator>::iterator
const_iterator
template<typename T, size_t SIMD_SIZE = CPPASSIST_SIMD_SIZE> using cppassist::vector< T, SIMD_SIZE >::const_iterator = typename std::vector<value_type, allocator>::const_iterator
size_type
template<typename T, size_t SIMD_SIZE = CPPASSIST_SIMD_SIZE> using cppassist::vector< T, SIMD_SIZE >::size_type = typename std::vector<value_type, allocator>::size_type
reference
template<typename T, size_t SIMD_SIZE = CPPASSIST_SIMD_SIZE> using cppassist::vector< T, SIMD_SIZE >::reference = typename std::vector<value_type, allocator>::reference
const_reference
template<typename T, size_t SIMD_SIZE = CPPASSIST_SIMD_SIZE> using cppassist::vector< T, SIMD_SIZE >::const_reference = typename std::vector<value_type, allocator>::const_reference
Constructor & Destructor Documentation
vector() [1/5]
template<typename T , size_t SIMD_SIZE> cppassist::vector< T, SIMD_SIZE >::vector ()
Referenced by cppassist::traverse_mt().
vector() [2/5]
template<typename T , size_t SIMD_SIZE> cppassist::vector< T, SIMD_SIZE >::vector (size_t count)
vector() [3/5]
template<typename T, size_t SIMD_SIZE> cppassist::vector< T, SIMD_SIZE >::vector (T * data, size_t count)
References cppassist::vector< T, SIMD_SIZE >::m_data.
vector() [4/5]
template<typename T, size_t SIMD_SIZE> cppassist::vector< T, SIMD_SIZE >::vector (const vector< T, SIMD_SIZE > & data)
vector() [5/5]
template<typename T, size_t SIMD_SIZE> cppassist::vector< T, SIMD_SIZE >::vector (vector< T, SIMD_SIZE > && data)
Member Function Documentation
data() [1/2]
template<typename T , size_t SIMD_SIZE> T * cppassist::vector< T, SIMD_SIZE >::data ()
References cppassist::vector< T, SIMD_SIZE >::m_data.
Referenced by cppassist::vector< T, SIMD_SIZE >::valueBegin(), and cppassist::vector< T, SIMD_SIZE >::valueEnd().
data() [2/2]
template<typename T , size_t SIMD_SIZE> const T * cppassist::vector< T, SIMD_SIZE >::data () const
References cppassist::vector< T, SIMD_SIZE >::m_data.
size()
template<typename T , size_t SIMD_SIZE> size_t cppassist::vector< T, SIMD_SIZE >::size () const
References cppassist::vector< T, SIMD_SIZE >::m_size.
Referenced by cppassist::add(), cppassist::div(), cppassist::mul(), cppassist::LogMessageBuilder::operator<<(), cppassist::vector< T, SIMD_SIZE >::resize(), cppassist::sqrt(), cppassist::sub(), and cppassist::vector< T, SIMD_SIZE >::valueEnd().
resize()
template<typename T , size_t SIMD_SIZE> void cppassist::vector< T, SIMD_SIZE >::resize (size_t size)
References cppassist::vector< T, SIMD_SIZE >::m_data, cppassist::vector< T, SIMD_SIZE >::m_size, and cppassist::vector< T, SIMD_SIZE >::size().
empty()
template<typename T , size_t SIMD_SIZE> bool cppassist::vector< T, SIMD_SIZE >::empty ()
References cppassist::vector< T, SIMD_SIZE >::m_data.
clear()
template<typename T , size_t SIMD_SIZE> void cppassist::vector< T, SIMD_SIZE >::clear ()
References cppassist::vector< T, SIMD_SIZE >::m_data, and cppassist::vector< T, SIMD_SIZE >::m_size.
chunkSize()
template<typename T , size_t SIMD_SIZE> size_t cppassist::vector< T, SIMD_SIZE >::chunkSize () const
References cppassist::vector< T, SIMD_SIZE >::m_data.
Referenced by cppassist::add(), cppassist::div(), cppassist::mul(), cppassist::sqrt(), cppassist::sub(), cppassist::traverse(), and cppassist::traverse_mt().
chunk() [1/2]
template<typename T , size_t SIMD_SIZE> value< T, SIMD_SIZE > & cppassist::vector< T, SIMD_SIZE >::chunk (size_t i)
References cppassist::vector< T, SIMD_SIZE >::m_data.
Referenced by cppassist::add(), cppassist::div(), cppassist::mul(), cppassist::sqrt(), cppassist::sub(), cppassist::traverse(), and cppassist::traverse_mt().
chunk() [2/2]
template<typename T , size_t SIMD_SIZE> const value< T, SIMD_SIZE > & cppassist::vector< T, SIMD_SIZE >::chunk (size_t i) const
References cppassist::vector< T, SIMD_SIZE >::m_data.
begin() [1/2]
template<typename T , size_t SIMD_SIZE> vector< T, SIMD_SIZE >::iterator cppassist::vector< T, SIMD_SIZE >::begin ()
References cppassist::vector< T, SIMD_SIZE >::m_data.
begin() [2/2]
template<typename T , size_t SIMD_SIZE> vector< T, SIMD_SIZE >::const_iterator cppassist::vector< T, SIMD_SIZE >::begin () const
References cppassist::vector< T, SIMD_SIZE >::m_data.
end() [1/2]
template<typename T , size_t SIMD_SIZE> vector< T, SIMD_SIZE >::iterator cppassist::vector< T, SIMD_SIZE >::end ()
References cppassist::vector< T, SIMD_SIZE >::m_data.
end() [2/2]
template<typename T , size_t SIMD_SIZE> vector< T, SIMD_SIZE >::const_iterator cppassist::vector< T, SIMD_SIZE >::end () const
References cppassist::vector< T, SIMD_SIZE >::m_data.
valueBegin() [1/2]
template<typename T , size_t SIMD_SIZE> T * cppassist::vector< T, SIMD_SIZE >::valueBegin ()
References cppassist::vector< T, SIMD_SIZE >::data().
valueBegin() [2/2]
template<typename T , size_t SIMD_SIZE> const T * cppassist::vector< T, SIMD_SIZE >::valueBegin () const
References cppassist::vector< T, SIMD_SIZE >::data().
valueEnd() [1/2]
template<typename T , size_t SIMD_SIZE> T * cppassist::vector< T, SIMD_SIZE >::valueEnd ()
References cppassist::vector< T, SIMD_SIZE >::data(), and cppassist::vector< T, SIMD_SIZE >::size().
valueEnd() [2/2]
template<typename T , size_t SIMD_SIZE> const T * cppassist::vector< T, SIMD_SIZE >::valueEnd () const
References cppassist::vector< T, SIMD_SIZE >::data(), and cppassist::vector< T, SIMD_SIZE >::size().
Member Data Documentation
m_size
template<typename T, size_t SIMD_SIZE = CPPASSIST_SIMD_SIZE> size_t cppassist::vector< T, SIMD_SIZE >::m_size protected
Referenced by cppassist::vector< T, SIMD_SIZE >::clear(), cppassist::vector< T, SIMD_SIZE >::resize(), and cppassist::vector< T, SIMD_SIZE >::size().
m_data
template<typename T, size_t SIMD_SIZE = CPPASSIST_SIMD_SIZE> std::vector<value<T, simd_size>, allocator> cppassist::vector< T, SIMD_SIZE >::m_data protected
Referenced by cppassist::vector< T, SIMD_SIZE >::begin(), cppassist::vector< T, SIMD_SIZE >::chunk(), cppassist::vector< T, SIMD_SIZE >::chunkSize(), cppassist::vector< T, SIMD_SIZE >::clear(), cppassist::vector< T, SIMD_SIZE >::data(), cppassist::vector< T, SIMD_SIZE >::empty(), cppassist::vector< T, SIMD_SIZE >::end(), cppassist::vector< T, SIMD_SIZE >::resize(), and cppassist::vector< T, SIMD_SIZE >::vector().
The documentation for this class was generated from the following files:
vector.h
vector.inl